
blueprint:
  name: "Automatizace pro ovlÃ¡dÃ¡nÃ­ Å¾aluziÃ­ (CCA)"
  description: |
    # â­ Automatizace pro ovlÃ¡dÃ¡nÃ­ Å¾aluziÃ­ (CCA) â­
    ### KomplexnÃ­ a vysoce konfigurovatelnÃ½ blueprint pro rolety a Å¾aluzie

    **Verze**: 2024.10.21
    **NÃ¡povÄ›da**: [VlÃ¡kno komunity](https://community.home-assistant.io/t/cover-control-automation-cca-a-comprehensive-and-highly-configurable-roller-blind-blueprint/680539) | **ZdrojovÃ½ kÃ³d**: [github.com/hvorragend](https://github.com/hvorragend/ha-blueprints/blob/main/blueprints/automation/cover_control_automation.yaml) | **HlÃ¡sit chyby**: [ProblÃ©my](https://github.com/hvorragend/ha-blueprints/issues)

    **Pokud byste mÄ› chtÄ›li podpoÅ™it nebo mi podÄ›kovat, kliknÄ›te zde:**
    ### ğŸ™ [Dar pÅ™es PayPal](https://www.paypal.com/donate/?hosted_button_id=NQE5MFJXAA8BQ) | [Kupte mi kÃ¡vu](https://buymeacoffee.com/herr.vorragend) ğŸ™

    <details>
    <summary><strong>Funkce</strong></summary>

    âœ… AutomatickÃ© otevÃ­rÃ¡nÃ­ a zavÃ­rÃ¡nÃ­ rolet
    âœ… VolnÄ› konfigurovatelnÃ© Äasy a akce
    âœ… Integrace s podmÃ­nkami poÄasÃ­ a Äasu
    âœ… ManuÃ¡lnÃ­ ovlÃ¡dÃ¡nÃ­ a moÅ¾nost doÄasnÃ©ho zastavenÃ­
    âœ… FlexibilnÃ­ plÃ¡novÃ¡nÃ­ a integrace do dalÅ¡Ã­ch automatizacÃ­
    </details>

    <details>
    <summary><strong>PotÅ™ebnÃ© komponenty</strong></summary>

    - Home Assistant 2024.10 nebo vyÅ¡Å¡Ã­
    - KompatibilnÃ­ Å¾aluzie nebo rolety, kterÃ© lze ovlÃ¡dat pÅ™es Home Assistant
    </details>

    <details>
    <summary><strong>PoznÃ¡mky</strong></summary>

    Tento blueprint poskytuje flexibilnÃ­ a pÅ™izpÅ¯sobitelnÃ© Å™eÅ¡enÃ­ pro ovlÃ¡dÃ¡nÃ­ Å¾aluziÃ­, vÄetnÄ› pokroÄilÃ½ch funkcÃ­ pro pÅ™izpÅ¯sobenÃ­ automatizace podle poÄasÃ­, Äasu a dalÅ¡Ã­ch podmÃ­nek.
    </details>
